package fr.nicknqck.roles.desc;

import org.bukkit.ChatColor;

public class AllDesc{
	// §c❤§r ❤ rouge
	public final static String coeur = "§c❤§r";
	public static String Coeur(String color) {
		return color+"❤§r";
	}
	public final static String Speed = "§eSpeed§r";
	public final static String Force = "§cForce§r";
	public final static String Resi = "§9Résistance§r";
	public final static String nuit = "§1nuit§r";
	public final static String jour = "§ejour§r";
	public final static String fireResi = "§6Fire Résistance§r";
	public final static String bar = ChatColor.DARK_GRAY+"§o§m-----------------------------------§r";
	public final static String regen = "§dRégénération§r";
	public final static String blind = "§1Blindness§r";
	public final static String slow = "§9Slowness§r";
	public final static String weak = "§7Weakness§r";
	public final static String items = ChatColor.BOLD+"Items: ";
	public final static String commande = ChatColor.BOLD + "Commande: ";
	public final static String effet = ChatColor.BOLD+"Effet: ";
	public final static String capacite = ChatColor.BOLD+"Capacité: ";
	public final static String role = "§lRôle§r:§6 ";
	public final static String point = "§8 • §r";
	public final static String objectifteam = "§fVotre objectif est de gagner avec le camp: ";
	public final static String objectifsolo = "§fVotre objectif est de gagner ";
	public final static String particularite = ChatColor.BOLD + "Particularité: ";
	public final static String nausee = "§2Nausée";
	static final String t =  "§fSi vous parvenez à tuez un joueur possédant le rôle de§6 Muzan§r vous obtiendrez "+Force+" 1 permanent, de plus votre§6 Dance du Dieu du Feu§r ne vous coutera plus de "+coeur+" permanent";
	public static final String chakra = "Vous possédez la nature de Chakra: ";
	public final static String tab = "§7     →";

	public static String[] Kyogai = new String[]{
			bar,
			"§lRôle: §r§6Kyogai",
			"",
            ChatColor.WHITE + "" + ChatColor.BOLD + " Choix: ",
            "",
            ChatColor.DARK_GRAY + " • " + ChatColor.WHITE + " Vous possédez au début de la partie le choix entre 2 camps (Solo & Démon)",
            "",
            ChatColor.GOLD+"Démon: "+ChatColor.WHITE+"En choisissant ce camp vous obtiendrez "+Force+" 1 §rla "+nuit+" ainsi que l'item§6 Tambour§r qui vous permettra via un clique droit de retourner une personne visée",
            "",
            ChatColor.GOLD+ "Solo: "+ChatColor.WHITE+"En choisissant ce camp, vous obtiendrez "+Force+" 1§r permanent ainsi que "+Resi+" 1§r la "+nuit+", vous obtiendrez aussi l'accès à l'item§6 Tambour §rqui vous permettra via un clique droit de retourner une personne visée,",
            "",
            "Vous aurez égalemenet l'item§6 Percussion Rapide§r vous activerez un passif d'une durée de§6 15 secondes§r qui vous permettra de faire que quand vous tapez un joueur il y aura 1 chance sur 5 qu'elle sois retourner",
            "",
            ChatColor.BOLD + " Amélioration: (Camp: Démon)",
            "",
            ChatColor.DARK_GRAY + " • " + ChatColor.WHITE + " Si vous parvenez à tuez un joueur possédant le rôle de: " + ChatColor.GOLD + "Tanjiro" + ChatColor.WHITE + " vous obtiendrez l'item§6 Percussion Rapide§r vous activerez un passif d'une durée de 10 secondes qui vous permettra de faire que quand vous tapez un joueur il y aura 1 chance sur 5 qu'elle sois retourner",
            "",
            ChatColor.BOLD + " Amélioration: (Camp: Solo)",
            "",
            ChatColor.DARK_GRAY + " • " + ChatColor.WHITE + " Si vous parvenez à tuez un joueur possédant le rôle de: " + ChatColor.GOLD + "Muzan" + ChatColor.WHITE + " votre Tambour ne retournera plus une personne mais toute les personnes (sauf vous) qui sont à moins de 30 blocs de vous, également vous obtiendrez 2"+coeur+" en plus permanent",
            "",
            bar
    };
	public static String[] KyogaiDemon = new String[]{
			bar,
			"§lRôle: §r§cKyogai§r (§cDémon§r)",
			"",
            ChatColor.BOLD+"Effet:§r",
            "",
            ChatColor.DARK_GRAY + " • " +Force+" 1§r la "+nuit,
            "",
            ChatColor.BOLD + "Item:",
            "",
            ChatColor.DARK_GRAY + " • " + ChatColor.GOLD + "Tambour:§r Vous permet via un clique droit de retourner une personne visée (§6Cooldown 60s§r)",
            "",
            ChatColor.BOLD + " Amélioration:",
            "",
            ChatColor.DARK_GRAY + " • " + "§r Si vous parvenez à tuez un joueur possédant le rôle de: " + ChatColor.GOLD + "Tanjiro" + ChatColor.WHITE + " vous obtiendrez l'item §6Percussion Rapide§r vous activerez un passif d'une durée de 10 secondes qui vous permettra de faire que quand vous tapez un joueur il y aura 1 chance sur 5 qu'elle sois retourner",
            "",
            bar
    };
	public static String[] KyogaiSolo = new String[]{
			bar,
			"§lRôle: §r§6Kyogai§r (§6Solo§r)",
			"",
			ChatColor.BOLD + " Effet: ",
            "",
            ChatColor.DARK_GRAY + " •§r "+Force+" 1 permanent "+Resi+" 1 la "+nuit,
            "",
            "§lItems: ",
            "",
            ChatColor.DARK_GRAY + " •§6 Tambour§r: Vous permet via un clique droit de retourner une personne visée (§6Cooldown 30s§r)",
            "",
            ChatColor.DARK_GRAY + " •§6 Percussion Rapide§r: Vous permet via un clique droit d'activer un passif (15s) qui vous permettra que des que vous tapez un joueur il y aura alors §61chance sur 5§r que ce dernier sois retourner (§6Cooldown 10m§r)",
            "",
            "Vous aurez égalemenet l'item §6Percussion Rapide§r vous activerez un passif d'une durée de §615 secondes§r qui vous permettra de faire que quand vous tapez un joueur il y aura 1 chance sur 5 qu'elle sois retourner",
            "",
            ChatColor.BOLD + " Amélioration:",
            "",
            ChatColor.DARK_GRAY + " • " + ChatColor.WHITE + " Si vous parvenez à tuez un joueur possédant le rôle de: " + ChatColor.GOLD + "Muzan" + ChatColor.WHITE + " votre Tambour ne retournera plus une personne mais toute les personnes (sauf vous) qui sont à moins de 30 blocs de vous, également vous obtiendrez 2"+coeur+" en plus permanent",
            "",
            bar
    };
	public static String[] Rui = new String[]{
			bar,
			"§lRôle: §r§cRui",
			"",
            "§lItems: ",
            "",
            ChatColor.DARK_GRAY + " • " + ChatColor.GOLD + ChatColor.BOLD + " Fils: " + ChatColor.WHITE + "Ouvre un menu vous permettant de choisir entre 4 différents fils: ",
            "",
            ""+ChatColor.RED + ChatColor.BOLD + "!!! " + ChatColor.WHITE + "Vous ne pouvez utiliser que 2 fils maximum en même temp, le cooldown entre deux choix est de 10s et aussi le cooldown dans le menu n'est pas actualisé en temp réel",
            "",
            ChatColor.DARK_GRAY + " • " + ChatColor.GOLD + ChatColor.BOLD + " Fils de Force: " + ChatColor.WHITE + "Vous donne "+Force+" 1 pendant 1 minutes"+ChatColor.GOLD+" Cooldown: 3m",
            "",
            ChatColor.DARK_GRAY + " • " + ChatColor.GOLD + ChatColor.BOLD + " Fils de Speed: " + ChatColor.WHITE + "Vous donne "+Speed+" 1 pendant 1 minutes"+ChatColor.GOLD+" Cooldown: 3m",
            "",
            ChatColor.DARK_GRAY + " • " + ChatColor.GOLD + ChatColor.BOLD + " Fils de Résistance: " + ChatColor.WHITE + "Vous donne "+Resi+" 1 pendant 1 minutes"+ChatColor.GOLD+" Cooldown: 3m",
            "",
            ChatColor.DARK_GRAY + " • " + ChatColor.GOLD + ChatColor.BOLD + " Fils de Régénération: " + ChatColor.WHITE + "Vous donne "+regen+" 1 pendant 30 secondes"+ChatColor.GOLD+" Cooldown: 3m",
            "",
            ChatColor.DARK_GRAY + " • " + ChatColor.GOLD + ChatColor.BOLD + " Pouvoir Sanginaire: " + ChatColor.WHITE + "Vous donne le pouvoir de tout vos fils d'un coup pendant"+ChatColor.GOLD+" 2m30 (Cooldown:8m)"+ChatColor.WHITE+", cependant il faut que tout les fils soit utilisable pour utiliser le pouvoir sanginaire",
            "",
            bar
    };
	public static String[] Daki = new String[] {
			bar,
			"§lRôle: §r§cDaki",
			"",
			ChatColor.BOLD+"Capacité: ",
			"",
			(ChatColor.DARK_GRAY+" • " +ChatColor.WHITE+"1 fois par partie vous pouvez réssucité"),
			"",
			ChatColor.BOLD+"Effet: ",
			"",
			(ChatColor.DARK_GRAY+" • " +Force+" 1 la nuit, "+Resi+" 1 à moins de 30 blocs de Gyutaro, Weakness 1 à moins de 15 blocs des rôles : Tengen, Tanjiro, Inosuke, ZenItsu, Nezuko"),
			"",
			ChatColor.BOLD+"Items: ",
			"",
			(ChatColor.DARK_GRAY+" • " +ChatColor.GOLD+ChatColor.BOLD+"Obi: "+ChatColor.WHITE+" En activant cette objet tout les joueurs étant à moins de 30 blocs (sauf les rôles: Tanjiro, Inosuke, ZenItsu, Tengen, Gyutaro et les démons) ne pourront plus bouger pendant 8 secondes"),
			"",
			(ChatColor.DARK_GRAY+" • "+ChatColor.GOLD+ChatColor.BOLD+"Troisième Oeil: "+ChatColor.WHITE+" Vous donne "+Speed+" 1 pendant 1 minutes"),
			"",
			(ChatColor.WHITE+""+ChatColor.BOLD+"Amélioration: "),
			"",
			(ChatColor.DARK_GRAY+" • " + ChatColor.WHITE+"A la mort de: "+ChatColor.GOLD+"Gyutaro"+ChatColor.WHITE+" peux importe qui le tue vous obtenez "+Resi+" 1 permanent, mais vous perdez aussi votre troisième oeil"),
			"",
			(ChatColor.DARK_GRAY+" • "+   ChatColor.WHITE+"A la mort de: "+ChatColor.GOLD+"Tanjiro OU Inosuke OU ZenItsu"+ChatColor.WHITE+" peux importe qui le/les tues vous perdez votre effet weakness proche des rôles: Tanjiro, Inosuke, ZenItsu, Tengen, Nezuko"),
			"",
			bar
	};
	public static String[] Demon_Simple = new String[] {
			bar,
			"§lRôle: §r§cDemon Simple",
			"",
			ChatColor.BOLD+"Effet: ",
			"",
			(ChatColor.DARK_GRAY+" • " +ChatColor.WHITE+"weakness 1 le jour, "+Force+" 1 la nuit"),
			"",
			(ChatColor.WHITE+""+ChatColor.BOLD+"Amélioration: "),
			"",
			(ChatColor.DARK_GRAY+" • " +ChatColor.WHITE+"Si vous parvenez à tuez un joueur "+" vous obtiendrez + 3% de "+Force),
			"",
			bar
	};
	public static String[] DemonMain = new String[] {
			bar,
			"§lRôle: §r§cDemon Main",
			"",
			ChatColor.BOLD+"Effet: ",
			"",
			("§8 • " +Force+" 1 la nuit"),
			"",
			ChatColor.BOLD+"Items: ",
			"",
			("§8 • " +ChatColor.GOLD+ChatColor.BOLD+"Pouvoir Sanginaire: "+ChatColor.WHITE+" En activant cette objet vous infligerez des dégats (1 "+coeur+") à tout les joueurs étant à moins de 30 blocs de vous"),
			"",
			(ChatColor.WHITE+""+ChatColor.BOLD+"Amélioration: "),
			"",
			("§8 • " + ChatColor.WHITE+"En tuant quelqu'un ayant le rôle de: "+ChatColor.GOLD+"Urokodaki"+ChatColor.WHITE+" vous obtiendrez "+Force+" 1 le jour"),
			"",
			("§8 • "+ChatColor.WHITE+"En tuant quelqu'un ayant le rôle de: "+ChatColor.GOLD+"Tanjiro OU Sabito OU Tomioka OU Makomo"+ChatColor.WHITE+" vous obtenez "+Resi+" 1 pendant 2 minutes"),
			"",
			bar
	};
	public static String[] Doma = new String[] {
			bar,
			"§lRôle: §r§cDoma",
			"",
			ChatColor.BOLD+"Effet: ",
			"",
			(ChatColor.DARK_GRAY+" • " +Force+" 1 la nuit"),
			"",
			ChatColor.BOLD+"Items: ",
			"",
			(ChatColor.DARK_GRAY+" • " +ChatColor.GOLD+ChatColor.BOLD+"Epouventaille de Glace: "+ChatColor.WHITE+"Épée en diamant tranchant 3"),
			"",
			(ChatColor.DARK_GRAY+" • " +ChatColor.GOLD+ChatColor.BOLD+"Pouvoir Sanginaire, Zone de Glace: "+ChatColor.WHITE+" En activant cette objet pendant 25 secondes tout les joueurs étant à moins de 30 blocs de vous obtiendront slowness 1 et les joueurs étant à moins de 5 blocs auront slowness 3"),
			"",
			(ChatColor.DARK_GRAY+" • "+ChatColor.GOLD+ChatColor.BOLD+"Pouvoir Sanginaire, Statut de Glace: "+ChatColor.WHITE+" En activant cette objet pendant 5 minutes en tapant un joueur avec votre Epouventaille de Glace vous aurez 1 chance sur 4 d'obtenir "+Resi+" 1 pendant 10s"),
			"",
			bar
	};
	public static String[] Gyokko = new String[] {
			bar,
			"§lRôle: §r§cGyokko",
			"",
			ChatColor.BOLD+"Effet: ",
			"",
			(ChatColor.DARK_GRAY+" • " +Force+" 1 la "+nuit),
			"",
			ChatColor.BOLD+"Items: ",
			"",
			(ChatColor.DARK_GRAY+" • " +ChatColor.GOLD+ChatColor.BOLD+"Pouvoir Sanginaire: "+ChatColor.WHITE+"Vous téléportera dans un rayon de 15 blocs au tour de vous (à la même couche que la ou vous êtes)"),
			"",
			(ChatColor.DARK_GRAY+" • "+ChatColor.GOLD+ChatColor.BOLD+"Forme Démoniaque: "+ChatColor.WHITE+"Quand vous activez votre Forme Démonique vous lancez un compte à rebours qui vous fera perdre 1"+coeur+" permanent toute les minutes, mais il vous donnera également des aventages très pratique comme: un plastron Thorns 3, "+Resi+" 1 Permanent"),
			"",
			ChatColor.DARK_GRAY+" • "+ChatColor.GOLD+ChatColor.BOLD+"Bulle: "+ChatColor.WHITE+"Crée une bulle d'eau autours de vous de rayon 8",
			"",
			(ChatColor.BOLD+"Amélioration: "),
			"",
			(ChatColor.DARK_GRAY+" • " +ChatColor.WHITE+"Si vous parvenez à tuez un joueur possédant le rôle de "+ChatColor.GOLD+"Muichiro"+ChatColor.WHITE+" vous obtiendrez force 1 le jour ainsi que des bottes depht strider 2"),
			"",
			bar
	};
	public static String[] Gyutaro = new String[] {
			bar,
			"§lRôle: §r§cGyutaro",
			"",
			ChatColor.BOLD+"Capacité: ",
			"",
			(ChatColor.DARK_GRAY+" • " +ChatColor.WHITE+"Tant que vous avez plus de 8"+coeur+" permanent vous pouvez réssussiter, en mourant vous réssuciter en perdant 1"+coeur+" permanent"),
			"",
			ChatColor.BOLD+"Effet: ",
			"",
			(ChatColor.DARK_GRAY+" • " +Force+" 1 la "+nuit+", "+Resi+" 1 à moins de 30 blocs de Daki"),
			"",
			ChatColor.BOLD+"Items: ",
			"",
			(ChatColor.DARK_GRAY+" • " +ChatColor.GOLD+ChatColor.BOLD+"Faucille:"+ChatColor.WHITE+" En activant cette objet vous activez votre vol de point de vie qui vous permettra d'enlever 2"+coeur+" non permanent à la personne la plus proche que vous pouvez voir, aussi vous fait gagner 1"+coeur+" permanent pendant 2 minutes"),
			"",
			(ChatColor.DARK_GRAY+" • "+ChatColor.GOLD+ChatColor.BOLD+"Pouvoir Sanginaire:"+ChatColor.WHITE+" Donne Aléatoiremenet à tout les joueurs étant à moins de 50 blocs de vous (sauf Daki et vous) Poison 1 pendant 30 secondes ou Poison 2 pendant 15 secondes"),
			"",
			(ChatColor.WHITE+""+ChatColor.BOLD+"Amélioration: "),
			"",
			(ChatColor.DARK_GRAY+" • " + ChatColor.WHITE+"A la mort de: "+ChatColor.GOLD+"Daki"+ChatColor.WHITE+" peux importe qui le tue vous récupérerez votre Troisième Oeil, ce qui vous permettra d'obtenir "+Speed+" 1 pendant 1 minutes en l'activant"),
			"",
			(ChatColor.DARK_GRAY+" • "+   ChatColor.WHITE+"En tuant un joueur possédant le rôle de: "+ChatColor.GOLD+"Tengen "+ChatColor.WHITE+" vous obtiendrez "+Force+" 1 le jour ce qui vous fera donc "+Force+" 1 permanent"),
			"",
			(ChatColor.DARK_GRAY+" • "+ChatColor.WHITE+" En tuant un joueur ayant le rôle de: "+ChatColor.GOLD+"ZenItsu, Inosuke, Nezuko, Tengen, Tanjiro"+ChatColor.WHITE+" vous obtiendrez 1"+coeur+" permanent supplémentaire"),
			"",
			bar
	};
	public static String[] Hantengu = new String[] {
			bar,
			"§lRôle: §r§cHantengu",
			"",
			ChatColor.BOLD+"Effet: ",
			"",
			(ChatColor.DARK_GRAY+" • " +ChatColor.WHITE+"(Si vous êtes Hantengu) "+Resi+" 2, Invisibilité 1 en enlevant son armure, Weakness 1 le jour"),
			"",
			ChatColor.BOLD+"Items: ",
			"",
			(ChatColor.DARK_GRAY+" • " +ChatColor.GOLD+ChatColor.BOLD+"Zohakuten: "+ChatColor.WHITE+"Pendant 5 minutes vous aurez "+Speed+" 1 et "+Resi+" 1, aussi quand vous taperez un joueur avec votre épée il y aura une chance sur 4 qu'il obtienne nausée 2 pendant 15 secondes"),
			"",
			(ChatColor.DARK_GRAY+" • "+ChatColor.GOLD+ChatColor.GOLD+"Sekido: "+ChatColor.WHITE+"Pendant 5 minutes vous aurez "+Force+" 1, aussi pendant que vous êtes transformés en Sekido quand vous faite 1 kill vous gagnez 5% de "+Force),
			"",
			(ChatColor.DARK_GRAY+" • "+ChatColor.GOLD+"Urogi: "+ChatColor.WHITE+"Pendant 5 minutes vous aurez "+Speed+" 1, JumpBoost 4 et NoFall vous pourez égamelement utilisé le pouvoir sanginaire de Urogi qui vous permettra de Fly pendant 5s (vous ne pouvez l'utiliser qu'une fois par transformation)"),
			"",
			(ChatColor.DARK_GRAY+" • "+ChatColor.GOLD+"Karaku: "+ChatColor.WHITE+"Pendant 5 minutes vous aurez "+Speed+" 1, aussi en utilisant le§6 Pouvoir Sanguinaire de Karaku§r vous téléporterez tout les joueurs 30 blocs plus haut"),
			"",
			bar
	};
	public static String[] Kaigaku = new String[] {
			bar,
			"§lRôle: §r§cKaigaku",
			"",
			ChatColor.BOLD+"Effet: ",
			"",
			(ChatColor.DARK_GRAY+" • " +Force+" 1 la "+nuit+", si pacté par Jigoro vous aurez "+Speed+" 1 permanent"),
			"",
			ChatColor.BOLD+"Items: ",
			"",
			(ChatColor.DARK_GRAY+" • " +ChatColor.GOLD+ChatColor.BOLD+"Troisième Mouvement: "+ChatColor.WHITE+" Inflige 2"+coeur+" de dégat au joueur proche via un§e éclair§f, Si vous n'êtes pas pacté par§e Jigoro§f vous obtiendrez également "+Speed+" 1 pendant 3min"),
			"",
			(ChatColor.DARK_GRAY+" • " +ChatColor.GOLD+ChatColor.BOLD+"Quatrième Mouvement: "+ChatColor.WHITE+" Vous téléporte sur la personne la plus proche visible et lui inflige 2"+coeur+" de dégat via un§e éclair"),
			"",
			(ChatColor.WHITE+""+ChatColor.BOLD+"Amélioration: "),
			"",
			(ChatColor.DARK_GRAY+" • " +ChatColor.WHITE+"Si vous parvenez à tuez un joueur ayant le rôle de: "+ChatColor.GOLD+"ZenItsu"+ChatColor.WHITE+" vos cooldown réduiront de§c 60 secondes§f a chaque utilisation"),
			"",
			bar
	};
	public static String[] Kokushibo = new String[] {
			bar,
			"§lRôle: §r§cKokushibo",
			"",
			ChatColor.BOLD+"Capacité: ",
			"",
			(ChatColor.DARK_GRAY+" • " +ChatColor.WHITE+"Vous possédez la régénération naturel à hauteur de 1 demi"+coeur+" toute les 15 secondes"),
			"",
			ChatColor.BOLD+"Effet: ",
			"",
			(ChatColor.DARK_GRAY+" • " +Speed+" 1 permanent, "+Force+" 1 la nuit"),
			"",
			ChatColor.BOLD+"Items: ",
			"",
			(ChatColor.DARK_GRAY+" • " +ChatColor.GOLD+ChatColor.BOLD+"Pouvoir Sanginaire: "+ChatColor.WHITE+"Vous donne une épée en diamant nommé "+ChatColor.RED+"Epée de la nuit§r qui est Sharpness 4, et qui remplace instantanément le "+jour+" par la "+nuit),
			"",
			(ChatColor.WHITE+""+ChatColor.BOLD+"Amélioration: "),
			"",
			(ChatColor.DARK_GRAY+" • " +ChatColor.WHITE+"Si vous parvenez à tuez un joueur vous obtiendrez 1 demi"+coeur+" permanent"),
			"",
			particularite,
            "",
            ChatColor.DARK_GRAY + " • Lorsque vous envoyez un message dans le§c chat§f commençant par un \"§c!§f\", vous permet de parler avec§c Muzan",
            "",
			bar
	};
	public static String[] KokushiboSolo = new String[] {
			bar,
			"§lRôle: §r§eKokushibo",
			"",
			ChatColor.BOLD+"Capacité: ",
			"",
			(ChatColor.DARK_GRAY+" • " +ChatColor.WHITE+"Vous possédez la régénération naturelle à hauteur de 1 demi"+coeur+" toute les 15 secondes"),
			"",
			ChatColor.BOLD+"Effet: ",
			"",
			(ChatColor.DARK_GRAY+" • " +Speed+" 1 et "+Force+" 1 permanent"),
			"",
			ChatColor.BOLD+"Items: ",
			"",
			(ChatColor.DARK_GRAY+" • " +ChatColor.GOLD+ChatColor.BOLD+"Pouvoir Sanginaire: "+ChatColor.WHITE+"Vous donne une épée en diamant nommé "+ChatColor.RED+"Epée de la nuit§r qui est Sharpness 4, et qui remplace instantanément le "+jour+" par la "+nuit),
			"",
			(ChatColor.WHITE+""+ChatColor.BOLD+"Amélioration: "),
			"",
			(ChatColor.DARK_GRAY+" • " +ChatColor.WHITE+"Si vous parvenez à tuez un joueur vous obtiendrez 3 minutes de "+Resi),
			"",
			bar
	};
	public static String[] Muzan = new String[] {
			bar,
			"§lRôle: §r§cMuzan",
			"",
			ChatColor.BOLD+"Capacité: ",
			"",
			(ChatColor.DARK_GRAY+" • " +ChatColor.WHITE+"Vous possédez la régénération naturel à hauteur de 1 demi"+coeur+" toute les 10 secondes"),
			"",
			ChatColor.BOLD+"Effet: ",
			"",
			(ChatColor.DARK_GRAY+" • " +Resi+" 1 permanent, "+Force+" 1 et "+Speed+" 1 la "+nuit),
			"",
			(ChatColor.WHITE+""+ChatColor.BOLD+"Amélioration: "),
			"",
			(ChatColor.DARK_GRAY+" • " +ChatColor.WHITE+"Si vous parvenez à tuer un joueur possédant le rôle de§a Nezuko "+ChatColor.WHITE+"vous obtiendrez "+Force+" 1 le "+jour+" et "+Resi+" 2 la "+nuit),
			"",
			(ChatColor.BOLD+"Commande: "),
			"",
			ChatColor.DARK_GRAY+" • "+"§6§l/ds give§r Vous permet en spécifiant un joueur de lui donner le pouvoir de l'§cinfection§r, il pourra alors via un item séléctionné un joueur pour le rallier au camp des§c démons§r ("+ChatColor.DARK_RED+"ATTENTION§r: ce pouvoir ne permet d'infecter que les rôles§f Slayers§r)",
			"",
			particularite,
			"",
			ChatColor.DARK_GRAY + " • Lorsque vous envoyez un message dans le§c chat§f commençant par un \"§c!§f\", vous permet de parler avec§c Kokushibo",
			"",
			bar
	};
	public static String[] Inosuke = new String[] {
			bar,
			"§lRôle: §r§aInosuke",
			"",
			ChatColor.BOLD+"Capacité: ",
			"",
			(ChatColor.DARK_GRAY+" • " +ChatColor.WHITE+"En utilisant une Lame de Nichirin vous en obtiendrez une deuxième "),
			"",
			ChatColor.BOLD+"Effet: ",
			"",
			(ChatColor.DARK_GRAY+" • " +Resi+" 1 la "+nuit),
			"",
			ChatColor.BOLD+"Items: ",
			"",
			(ChatColor.DARK_GRAY+" • " +ChatColor.GOLD+ChatColor.BOLD+"Perforation: "+ChatColor.WHITE+"Après activation de ce Croc la prochaine personne que vous taperez prendra 1"+coeur+" non permanent en plus de votre coup"),
			"",
			(ChatColor.DARK_GRAY+" • "+ChatColor.GOLD+ChatColor.BOLD+"Mutilation Furieuse: "+ChatColor.WHITE+"En activant cette objet tout les joueurs dans un rayon de 30 blocs au tour de vous prendront 1,5"+coeur+" de dégat"),
			"",
			(ChatColor.DARK_GRAY+" • "+ChatColor.GOLD+ChatColor.BOLD+"Taillade Ondulante Divine: "+ChatColor.WHITE+"En activant cette objet vous perdez 2"+coeur+" non permanent et gagner l'effet "+Force+" 1 pendant 2 minutes"),
			"",
			(ChatColor.WHITE+""+ChatColor.BOLD+"Amélioration: "),
			"",
			(ChatColor.DARK_GRAY+" • " +ChatColor.WHITE+"Si vous parvenez à tuez un joueur possédant le rôle de: "+ChatColor.GOLD+"Doma"+ChatColor.WHITE+" vous n'aurez plus de malus avec la Taillade Ondulante Divine"),
			"",
			bar
	};
	public static String[] Kanao = new String[] {
			bar,
			"§lRôle: §r§aKanao",
			"",
			ChatColor.BOLD+"Effet: ",
			"",
			(ChatColor.DARK_GRAY+" • " +ChatColor.GREEN+"NoFall"),
			"",
			ChatColor.BOLD+"Items: ",
			"",
			(ChatColor.DARK_GRAY+" • "+ChatColor.GOLD+ChatColor.BOLD+"Hanagoromo Pourpre: "+ChatColor.WHITE+"Vous donne "+Force+" 1 pendant 1 minutes 30 secondes"),
			"",
			(ChatColor.DARK_GRAY+" • " +ChatColor.GOLD+ChatColor.BOLD+"Tourbillon de Pêche: "+ChatColor.WHITE+"Vous donne "+Speed+" 1 pendant 3 minutes et jumpboost 2 pendant 30 secondes"),
			"",
			(ChatColor.WHITE+""+ChatColor.BOLD+"Amélioration: "),
			"",
			(ChatColor.DARK_GRAY+" • " +ChatColor.WHITE+"Si vous parvenez à tuez un joueur possédant le rôle de "+ChatColor.GOLD+"Doma"+ChatColor.WHITE+" l'objet de shinobu pour empoisonner"),
			"",
			bar
	};
	public static String[] Makomo = new String[] {
			bar,
			"§lRôle: §r§aMakomo",
			"",
			ChatColor.BOLD+"Effet: ",
			"",
			(ChatColor.DARK_GRAY+" • " +Speed+" 1 permanent"),
			"",
			ChatColor.BOLD+"Items: ",
			"",
			(ChatColor.DARK_GRAY+" • " +ChatColor.GOLD+ChatColor.BOLD+"Souffle de l'Eau: "+ChatColor.WHITE+"Vous donne "+Force+" 1 pendant 2 minutes"),
			"",
			(ChatColor.WHITE+""+ChatColor.BOLD+"Amélioration: "),
			"",
			(ChatColor.DARK_GRAY+" • " +ChatColor.WHITE+"Si vous parvenez à tuez un joueur possédant le rôle de: "+ChatColor.GOLD+"Démon Main"+ChatColor.WHITE+" vous obtiendrez 10% de "+Speed+" en plus"),
			"",
			bar
	};
	public static String[] Nezuko = new String[] {
			bar,
			"§lRôle: §r§aNezuko",
			"",
		ChatColor.BOLD+"Capacité: ",
		"",
		(ChatColor.DARK_GRAY+" • " +ChatColor.WHITE+"Vous possédez la régénération naturel à hauteur de 1 demi"+coeur+" toute les 20 secondes"+ChatColor.GOLD+" (la "+nuit+")"),
		"",
		ChatColor.BOLD+"Effet: ",
		"",
		(ChatColor.DARK_GRAY+" • " +Force+" 1 la "+nuit+" et "+Resi+" 1 à moins de 30 blocs d'un joueur possédant le rôle de Tanjiro"),
		"",
		ChatColor.BOLD+"Items: ",
		"",
		(ChatColor.DARK_GRAY+" • " +ChatColor.GOLD+ChatColor.BOLD+"Pouvoir Sanginaire: "+ChatColor.WHITE+"Pendant§6 15s§r les joueurs que vous taperez seront automatiquement§e§l brulé§r également pendant 5s vous obtenez§d "+regen+" 5§r, également des particules émaneront de vous"),
		"",
		ChatColor.DARK_GRAY+"§o§m-----------------------------------"
	};
	public static String[] Sabito = new String[] {
			bar,
			"§lRôle: §r§aSabito",
			"",
			ChatColor.BOLD+"Effet: ",
			"",
			(ChatColor.DARK_GRAY+" • " +Resi+" 1 la "+nuit),
			"",
			ChatColor.BOLD+"Items: ",
			"",
			(ChatColor.DARK_GRAY+" • " +ChatColor.GOLD+ChatColor.BOLD+"Souffle de l'Eau: "+ChatColor.WHITE+"Pendant 2 minutes vous obtiendrez "+Speed+" 1"),
			"",
			(ChatColor.WHITE+""+ChatColor.BOLD+"Amélioration: "),
			"",
			(ChatColor.DARK_GRAY+" • " +ChatColor.WHITE+"A la mort de: "+ChatColor.GOLD+"Tomioka"+ChatColor.WHITE+" votre Souffle de l'eau vous donnera "+Speed+" 2 au lieu de "+Speed+" 1, votre cooldown réduira également de 30 secondes (cumulable)"),
			"",
			(ChatColor.DARK_GRAY+" • " +ChatColor.WHITE+"Si vous parvenez à tué un joueur possédant le rôle de: "+ChatColor.GOLD+"Démon Main"+ChatColor.WHITE+" votre Souffle de l'eau vous donnera "+Force+" 1 pendant 3 minutes, votre cooldown réduira également de 30 secondes (cumulable)"),
			"",
			bar
	};
	public static String[] Tanjiro = new String[] {
			bar,
			"§lRôle: §r§aTanjiro",
			"",
			ChatColor.BOLD+"Effet: ",
			"",
			(ChatColor.DARK_GRAY+" • " +Speed+" 1 le "+jour),
			"",
			ChatColor.BOLD+"Items: ",
			"",
			(ChatColor.DARK_GRAY+" • " +ChatColor.GOLD+ChatColor.BOLD+"Dance du Dieu du Feu: "+ChatColor.WHITE+"Vous donne "+Resi+" 1 et "+fireResi+" 1 pendant 3 minutes, pendant la première minutes lorsque vous tapez un joueur vous le mettrez en feu, 3 minutes après activation vous perdrez 2"+coeur+" permanent"),
			"",
			(ChatColor.WHITE+""+ChatColor.BOLD+"Amélioration: "),
			"",
			ChatColor.DARK_GRAY+" • " +t,
			"",
			ChatColor.BOLD + " Commande: ",
            "",
            ChatColor.DARK_GRAY + " • " + ChatColor.GOLD+"/ds sentir"+ChatColor.RESET+ " Permet de savoir combien il y à de démon autours de vous",
            "",
			bar
	};
	public static String[] Urokodaki = new String[] {
			bar,
			"§lRôle: §r§aUrokodaki",
			"",
			ChatColor.BOLD+"Effet: ",
			"",
			(ChatColor.DARK_GRAY+" • " +Force+" 1 dans l'eau"),
			"",
			ChatColor.BOLD+"Items: ",
			"",
			(ChatColor.DARK_GRAY+" • " +ChatColor.GOLD+ChatColor.BOLD+"Souffle de l'Eau: "+ChatColor.WHITE+"Vous donne "+Speed+" 1 pendant 2 minutes"),
			"",
			(ChatColor.DARK_GRAY+" • "+ChatColor.GOLD+ChatColor.BOLD+"Botte d'Ancien pillier de l'Eau: "+ChatColor.WHITE+"Enchantée Depth Strider 2 et Protection 2"),
			"",
			(ChatColor.WHITE+""+ChatColor.BOLD+"Amélioration: "),
			"",
			(ChatColor.DARK_GRAY+" • " +ChatColor.WHITE+"A la mort des rôles: "+ChatColor.GOLD+"Tomioka, Tanjiro, Makomo, Sabito"+ChatColor.WHITE+" vous gagnez aléatoirement sois: §c5%§r de "+Force+" sois§b 5%§r de "+Speed),
			"",
			bar
	};
	public static String[] Jigoro = new String[] {
			bar,
			"§lRôle: §r§6Jigoro",
			"",
			ChatColor.BOLD+"Effet: ",
			"",
			(ChatColor.DARK_GRAY+" • " +Speed+" 1 permanent, "+Resi+" 1 permanent"),
			"",
			ChatColor.BOLD+"Items: ",
			"",
			ChatColor.DARK_GRAY+" • " +ChatColor.GOLD+ChatColor.BOLD+"Zone De Foudre:§f Crée une zone circulaire de 5 blocs de rayon, délimitée par des particules, dans laquelle vous recevrez l'effet "+regen+" 1 pendant 15s. Toutes les 4 secondes, un éclair infligeant 2"+coeur+" apparaîtra sur les joueurs présent dans la zone.",
			"",
			(ChatColor.WHITE+""+ChatColor.BOLD+"Amélioration: "),
			"",
			(ChatColor.DARK_GRAY+" • " +ChatColor.WHITE+"Si vous parvenez à tué un joueur possédant le rôle de§a Zen'Itsu§f vous obtiendrez "+Force+" 1 le "+jour+ChatColor.WHITE+" et aussi l'accès au"+ChatColor.GOLD+" Premier Mouvement du Souffle de la Foudre."),
			"",
			(ChatColor.DARK_GRAY+" • " +ChatColor.WHITE+"Si vous parvenez a tué un joueur possédant le rôle de§c Kaigaku§f vous obtiendrez " +Force+" 1 la "+nuit+ChatColor.WHITE+" mais également l'accès au:"+ChatColor.GOLD+" Quatrième Mouvement du Souffle de la Foudre."),
			"",
			bar
	};
	public static String[] Yoriichi = new String[] {
			bar,
			"§lRôle: §r§6Yoriichi",
			"",
			ChatColor.BOLD+"Effet: ",
			"",
			(ChatColor.DARK_GRAY+" • " +Speed+" 1 et "+Force+" 1 permanents, "+Resi+" 1 le "+jour),
			"",
			ChatColor.BOLD+"Items: ",
			"",
			(ChatColor.DARK_GRAY+" • " +ChatColor.GOLD+ChatColor.BOLD+"Souffle du Soleil:§f En activant cet objet vous activerez un passif qui est que quand vous tapez un joueur il perdra automatiquement son absorption"),
			"",
			(ChatColor.WHITE+""+ChatColor.BOLD+"Amélioration: "),
			"",
			(ChatColor.DARK_GRAY+" • " +ChatColor.WHITE+"Si vous parvenez à tuer un joueur possédant le rôle de "+ChatColor.GOLD+"Kokushibo"+ChatColor.WHITE+" vous obtiendrez "+Resi+" 1 la "+nuit),
			"",
			bar
	};
	public static String[] Enmu = new String[] {
			bar,
			"§lRôle: §r§cEnmu",
			"",
			ChatColor.BOLD+"Effet: ",
			"",
			(ChatColor.DARK_GRAY+" • " +Force+" 1 la "+nuit),
			"",
			ChatColor.BOLD+"Item: ",
			"",
			(ChatColor.DARK_GRAY+" • " +ChatColor.GOLD+ChatColor.BOLD+"Pouvoir Sanginaire:"+ChatColor.WHITE+" Vous permet d'endormir la personne visé pendant"+ChatColor.GOLD+" 10s§r (ne fonctionne pas sur les joueurs dont le rôle est Nezuko ou dont le camp est Demon), le joueur endormie ne pourra pas être tapée pendant ce cours lapse de temp"),
			"",
			bar
	};
	public static String[] Kagaya = new String[] {
			bar,
			"§lRôle: §r§aKagaya",
			"",
			(ChatColor.WHITE+""+ChatColor.BOLD+"Commande: "),
			"",
			(ChatColor.DARK_GRAY+" • " +ChatColor.GOLD+ChatColor.BOLD+"/ds role:"+ChatColor.WHITE+" Vous donne la possibilité de choisir un pacte entre 3"),
			"",
			ChatColor.DARK_GRAY+" • "+ChatColor.GOLD+ChatColor.BOLD+"1§r: Vous offre la possibilité de voir la vie au dessus des joueurs également vous obtenez weakness 1 le jour et "+Resi+" 1 la "+nuit,
			"",
			ChatColor.DARK_GRAY+" • "+ChatColor.GOLD+ChatColor.BOLD+"2§r: Vous octroie 2"+coeur+" permanent supplémentaire ainsi que "+Resi+" 1 le "+jour,
			"",
			ChatColor.DARK_GRAY+" • "+ChatColor.GOLD+ChatColor.BOLD+"3§r: Vous donne le nom d'un pillier aléatoire parmis ceux encore en vie ainsi que "+Resi+" 1 à moins de 30blocs de lui",
			"",
			bar
	};
	public static String[] Susamaru = new String[] {
			bar,
			"§lRôle: §r§cSusamaru",
			"",
			ChatColor.BOLD+"Items: ",
			"",
			(ChatColor.DARK_GRAY+" • " +ChatColor.GOLD+ChatColor.BOLD+"Ballon:"+ChatColor.WHITE+" Arc power 6 ayant des modes différents (naturellement mode 1)"),
			"",
			ChatColor.DARK_GRAY+" • "+ChatColor.GOLD+ChatColor.BOLD+"1§r: Quand vous tirez avec ce mode sa créera une explosion à l'impacte (Cooldown =§6 15s§r, Clique gauche pour changer de mode",
			"",
			ChatColor.DARK_GRAY+" • "+ChatColor.GOLD+ChatColor.BOLD+"2§r: Quand vous tirez avec ce mode vous suivrez la flèche jusqu'à son atterissage (Cooldown =§6 60s§r), Clique gauche pour changer de mode",
			"",
			bar
	};
	public static String[] Furuto = new String[] {
			bar,
			"§lRôle: §r§cFuruto",
			"",
           "§lEffet: ",
            "",
            ChatColor.DARK_GRAY + " • " + Force + " 1 la "+nuit,
            "",
            "§lItems: ",
            "",
            ChatColor.DARK_GRAY + " • " + ChatColor.GOLD + ChatColor.BOLD + "Flûte:§r En faisant un clique droit avec cette objet vous accorderez à tout les démons autours de vous un effet aléatoire en fonction de s'il fait jour ou pas (chaque effet décrit dur 1 minute)",
            "",
            ChatColor.GOLD+"En journée§r: "+Speed+" 1, "+Force+" 1, "+Resi+" 1, Jump Boost 1,",
            "",
            ChatColor.GOLD+"De nuit§r: "+Speed+" 2, "+Speed+" 1, "+Resi+" 1, Jump Boost 2",
            "",
            bar	
	};
	public static String[] JigoroV2 = new String[] {
			bar,
			"§lRôle: §r§6Jigoro",
			"",
           "§lEffet: ",
            "",
            ChatColor.DARK_GRAY + " • " + Speed + " 1 permanent",
            "",
            "§lItems: ",
            "",
            ChatColor.DARK_GRAY + " • " + ChatColor.GOLD + ChatColor.BOLD + "Vitesse:§r Permet d'obtenir "+Speed+" 3",
            "",
            ChatColor.BOLD + " Commande: ",
            "",
            ChatColor.DARK_GRAY + " • " + ChatColor.GOLD + ChatColor.BOLD + "/ds role:§r Permet de choisir un pacte parmi 3",
            "",
            ChatColor.GOLD+"Pacte 1§r: Vous devrez gagner seul en tant que rôle entièrement§6 solitaire§r pour ce faire vous obtiendrez "+Force+" 1 permanent§r, de plus vous obtiendrez "+Resi+" 1 le jour si vous tuez§a ZenItsu§r ainsi que "+Resi+" 1 la "+nuit+" si vous tuez§c Kaigaku§r, pour chaque kill de vos disciples vous récupérerez 10% de "+Speed,
            "",
            ChatColor.GOLD+"Pacte 2§r: Vous devrez gagner avec§c Kaigaku§r pour ce faire vous et lui disposez de l'effet "+Resi+" 1 à moins de 50blocs de lui ainsi que lorsque l'un de vous fait un kill vous gagnez tout les deux§c 1/2"+coeur+" permanent, de plus vous disposez d'un chat avec ce dernier via la commande§6 /ds chat, si vous ou§c Kaigaku§f parvenez à tuer§a Zen'Itsu§f vous obtiendrez l'effet§c Force I§f permanent",
            "",
            ChatColor.GOLD+"Pacte 3§r: Vous devrez gagner avec§a ZenItsu§r pour ce faire vous et lui  disposez de l'effet "+Resi+" 1 permanent, également vous possédez tous les deux l'effet§c "+Force+"§c 1§r à moins de 20blocs, pour vous aider à vous retrouver vous deux possédez une flèche pointant vers l'autre, si l'un de vous deux tue§c Kaigaku§r vous obtiendrez§6 "+Speed+"§b 2§r en-dessous de 5"+coeur,
            "",
            bar	
	};
	public static String[] HantenguV2 = new String[] {
			bar,
			"§lRôle: §r§cHantenguV2",
			"",
			ChatColor.BOLD+"Effet: ",
			"",
			(ChatColor.DARK_GRAY+" • " +ChatColor.WHITE+"(Si vous êtes Hantengu)§b "+Speed+" 2§r, Invisibilité 1 et§a No Fall§r en enlevant son armure, "+weak+" 1 permanent"),
			"",
			ChatColor.BOLD+"Items: ",
			"",
			(ChatColor.DARK_GRAY+" • " +ChatColor.GOLD+ChatColor.BOLD+"Materialisation des émotions: "+ChatColor.WHITE+"Ouvre un menu vous offrant la possibilité de choisir entre plusieurs clone de vous via un arbre de compétence, la première fois vous aurez le choix entre§c Karaku§r et§c Sekido§r puis entre§6Urogi§r et§6 Urami§r (si vous avez choisis§c Karaku§r) sinon entre§6 Aizetsu§r et§6 Urami§r (si vous avez choisis§c Sekido§r), puis à la toute fin vous aurez quoi qu'il arrive accès à§6 Zohakuten"),
			"",
			ChatColor.RED+"Karaku§r: Vous donne "+Speed+" 1 permanent ainsi que l'item§6 Vent§r qui vous permettra de tp les joueurs autours de vous§6 50blocs§r en hauteur",
			"",
			ChatColor.RED+"Sekido§r: Vous donne "+Force+" 1 permanent ainsi que l'item§6 Kakkhara§r qui via un clique droit créera un§e éclair§r sur tout les joueurs non-démon étant à moins de§6 25blocs§r qui leur infligera 2"+coeur+" ainsi que "+blind+" 1 et§9 "+slow+" 4§r pendant§l 4s",
			"",
			ChatColor.GOLD+"Urogi§r: Vous donne "+Speed+" 1 et "+Force+" 1 permanent ainsi que l'item§6 Urogi§r qui vous permettra de gagner l'effet§2 Jump Boost 4§r ainsi que 2 Double Jump qui vous propulseront d'environ 20blocs (Cooldown double jump: 30s), vous recevrez également l'item§6 Cri Sonique§r la personne visée obtiendra "+slow+" 1,§a Nausée 1§r et "+weak+" 1 pendant§6 30s",
			"",
			ChatColor.GOLD+"Urami§r: Vous donne "+Resi+" 2 ainsi que "+weak+" 1 permanent, via ce clone si vous mourrez avec vous réssuciter en temp qu'Hantengu mais avec 3"+coeur+" permanent en moins ",
			"",
			ChatColor.GOLD+"Aizetsu§r: Vous donne "+Force+" 1 permanent ainsi que 2"+coeur+" supplémentaire, vous obtiendrez via ce clone une épée nommé§6 Yari§r qui vous permettra via un clique droit de ne plus prendre de dégat pendant§6 5s",
			"",
			ChatColor.GOLD+"§oZohakuten§r: Vous donne "+Force+" 1 et "+Resi+" 1§r permanent ainsi qu'une "+regen+" naturelle de 0,5"+coeur+" toute les§6 15s§r de plus vous obtiendrez différent item en fonction des clones que vous avec choisis précédemment",
			"",
			bar
	};
	public static String[] JigoroV2Pacte1 = new String[] {
			bar,
			"§lRôle: §r§6Jigoro",
			"",
           "§lEffet: ",
            "",
            ChatColor.DARK_GRAY + " • " + ChatColor.WHITE + "§b "+Speed+" 1§r et§c "+Force+" 1§r permanent",
            "",
            "§lItems: ",
            "",
            ChatColor.DARK_GRAY + " • " + ChatColor.GOLD + ChatColor.BOLD + "Vitesse:§r Permet d'obtenir "+Speed+" 3",
            "",
            ChatColor.BOLD + "Pacte 1: ",
            "",
            "Vous gagner seul, pour ce faire vous obtiendrez§6 "+Resi+" 1 le jour en tuant§a ZenItsu§r ainsi que§6 "+Resi+" 1 la "+nuit+" si vous tuez§c Kaigaku§r, de plus pour chaque kill de vos disciple effectué vous récupérerez 10% de "+Speed,
            "",
            bar	
	};
	public static String[] JigoroV2Pacte2 = new String[] {
			bar,
			"§lRôle: §r§6Jigoro",
			"",
           "§lEffet: ",
            "",
            ChatColor.DARK_GRAY + " • " + ChatColor.WHITE + "§b "+Speed+" 1§r permanent",
            "",
            "§lItems: ",
            "",
            ChatColor.DARK_GRAY + " • " + ChatColor.GOLD + ChatColor.BOLD + "Vitesse:§r Permet d'obtenir "+Speed+" 3",
            "",
            ChatColor.BOLD + "Pacte 2: ",
            "",
            "Vous gagner en duo avec§c Kaigaku§r, pour ce faire vous et§c lui§r obtenez l'effet§3 "+Resi+" 1§r à moins de 50blocs l'un de l'autre, de plus quand§c Kaigaku§r ou vous faite un kill vous deux obtenez 1 demi"+coeur+" permanent, pour finir vous disposer d'un chat en commun via la commande§6 /ds chat",
            "",
            bar	
	};
	public static String[] JigoroV2Pacte3 = new String[] {
			bar,
			"§lRôle: §r§6Jigoro",
			"",
           "§lEffet: ",
            "",
            ChatColor.DARK_GRAY + " • " + ChatColor.WHITE + "§b "+Speed+" 1§r et§3 "+Resi+" 1§r permanent",
            "",
            "§lItems: ",
            "",
            ChatColor.DARK_GRAY + " • " + ChatColor.GOLD + ChatColor.BOLD + "Vitesse:§r Permet d'obtenir "+Speed+" 3",
            "",
            ChatColor.BOLD + "Pacte 3: ",
            "",
            "Vous gagner en duo avec§a ZenItsu§r, pour ce faire vous et§a lui§r obtenez l'effet§c "+Force+" 1§r à moins de 20blocs l'un de l'autre et l'effet§3 "+Resi+" 1§r permanent, de plus si vous ou§a ZenItsu§r parvenez à tué§c Kaigaku§r vous gagnerez§b "+Speed+" 2§r en dessous de 5"+coeur,
            "",
            bar	
	};
	public static String[] Demon_SimpleV2 = new String[] {
            bar,
            "§lRôle: §r§cDemon_SimpleV2",
            "",
           "§lEffet: ",
            "",
            ChatColor.DARK_GRAY + " • " + ChatColor.WHITE + "§b Weakness§r de "+jour+" et§3 "+Force+" 1§r de "+nuit,
            "",
            ChatColor.BOLD + "Améliration: ",
            "",
            ChatColor.DARK_GRAY + " • " + ChatColor.WHITE + "A votre premier kill vous perdez votre Weakness le "+jour+" de plus, plus vous obtiendrez de kill plus vous obtiendrez d'effet",
            "", 
            ChatColor.DARK_GRAY + " • " + ChatColor.RED + "2 kill:" + ChatColor.WHITE + " Vous obtenez 10% de "+Speed,
            "", 
            ChatColor.DARK_GRAY + " • " + ChatColor.RED + "3 kill:" + ChatColor.WHITE + " Vous obtenez 10% de "+Force+" supplémentaire",
            "", 
            ChatColor.DARK_GRAY + " • " + ChatColor.RED + "4 kill:" + ChatColor.WHITE + " Vous obtenez 10% de "+Resi,
            "", 
            ChatColor.DARK_GRAY + " • " + ChatColor.RED + "6 kill:" + ChatColor.WHITE + " Vous obtenez un item nommé transformation qui à son activation vous octroie l'effet "+Resi+" pendant 3min",
            "",
            ChatColor.DARK_GRAY + " • " + ChatColor.WHITE + "Vous possèdez l'identité aléatoire d'une lune suppérieur",
            "",
            bar
    };
	public static String[] Hotaru = new String[] {
            bar,
            "§lRôle:§r§a Hotaru",
            "",
            commande,
            "",
            ChatColor.DARK_GRAY + " • " + ChatColor.GOLD + "§l/ds lame§r: En spécifiant un joueur celà permet de savoir si le joueur spécifié possède une lame de Nichirin ou non, s'il en possède une vous saurez quel lame le joueur possède",
            "",
            ChatColor.DARK_GRAY + " • " + ChatColor.GOLD + "§l/ds role§r: Vous permet de choisir une lame de Nichirin",
            "",
            ChatColor.DARK_GRAY + " • " + ChatColor.GOLD + "§l/ds unbreak§r: En spécifiant un joueur celà vous permet de rendre la lame de ce joueur incassable",
            "",
            ChatColor.DARK_GRAY + " • " + ChatColor.GOLD + "§l/ds repair§r: En spécifiant un joueur celà vous permet d'augmenter la durabilité de sa lame de 40, 5 Utilisations maximum",
            "",
            bar
    };
    public static String[] Kumo = new String[] {
    		bar,
    		ChatColor.BOLD+"Rôle:§r§a Kumo",
    		"",
    		effet,
    		"",
    		"§8 • "+weak+" 1 le "+jour+", "+Force+" 1 la "+nuit,
    		items,
    		"",
    		"§8 • "+ChatColor.GOLD+"Emprisonnement dans la toile§r: Emprisonne le joueur visée dans des toiles d'arraignées",
    		"",
    		"§8 • "+ChatColor.GOLD+"Prison de toile§r: Crée une zone de 15blocs autours de vous en toile d'arraignée, en utilisant cette capacité vous perdez votre "+weak+" s'il fait "+jour,
    		"",
    		bar
    };
    public static String[] Nakime = new String[] {
            bar,
            role+"Nakime",
            "",
            effet,
            "",
            point+weak+" 1 permanent sauf dans votre cage ou une fois à l'intérieur vous possédez "+Force+" 1, "+Resi+" 1 ainsi que§a NoFall",
            "",
            items,
            "",
            point+"§cCage§f: Vous téléporte vous ainsi que toute les personnes étant à moins de 20blocs de vous dans la§6 cage de Nakime§f, de plus quand un joueur meurt dans cette cage son rôle n'est pas afficher dans le chat au yeux des autres joueur exepté§c Muzan§f et§c vous§f",
            "",
            commande,
            "",
            point+"§7/§cds return§7: Vous permet d'éjécter tout les joueurs étant dans votre§c cage de Nakime§7 (dont vous)",
            "",
            bar
    };
}
