name: UHC-Meetup
main: fr.nicknqck.Main
version: 2.2
author: NickNqck
commands:
  ds:
    description: All Commands about DemonSlayer-UHC-Meetup Plugin
    usage: /ds [role/list/doc/discord/lame]
    aliases: [ds]
  admindsuhc:
    description: All Admin Commands about DemonSlayer-UHC-Meetup Plugin
    usage: /a [nuit/jour]
    aliases: [a]
  kr:
    description: Pour les commandes du Krystal UHC
  discord:
    description: Donne le discord
  aot:
    description: Fait partie des roles AotUHC
    aliases: [aot]
  ns:
    description: Fait partie des roles NarutoUHC
    aliases: [ns]
  drop:
    description: Permet de drop le ou les items en main
  claim:
    description: Permet de claim les des items de role
  mumble:
    description: Permet d'obtenir le mumble
  say:
    description: Custom of /say commands
    permission: host.say
  gamemode:
    description: Custom of /gamemode commands
  gm:
    description: Addon of /gamemode
  wl:
    description: Addon of /whitelist
  whitelist:
    description: Custom of /whitelist commands
    permission: host.wl
  me:
    description: Custom from vanilla /me command
    permission: me.say
  color:
    description: Permet de colorier les autres joueurs de la partie
  pack:
    description: Permet d'obtenir le pack de texture de l'uhc
    usage: /pack
  setting:
    description: Permet de paramétrer certaine chose compatible
    usage: /setting ou /settings
  settings:
    description: Permet de paramétrer certaine chose compatible
    usage: /setting ou /settings
  info:
    description: Permet d'obtenir vos propres informations
    usage: /info